name: odms
description: Developed By MD. Ismail Hosen James.
publish_to: none
version: 1.6.9+18

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  awesome_notifications: ^0.9.3+1
  awesome_notifications_core: ^0.9.3
  bottom_picker: ^2.8.0
  clipboard: ^0.1.3
  connectivity_plus: ^6.0.5
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  email_validator: ^3.0.0
  fluentui_system_icons: ^1.1.252
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_foreground_task: ^8.10.4
  flutter_inappwebview: ^6.1.5
  flutter_launcher_icons: ^0.14.1
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.1
  flutter_polyline_points: ^2.1.0
  fluttertoast: ^8.2.8
  font_awesome_flutter: ^10.7.0
  gap: ^3.0.1
  geocoding: ^3.0.0
  geolocator: ^13.0.1
  get: ^5.0.0-release-candidate-9.2.1
  google_fonts: ^6.2.1
  google_maps_flutter: ^2.9.0
  google_places_flutter: ^2.0.9
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.2.2
  intl: ^0.19.0
  loading_animation_widget: ^1.2.1
  path_provider: ^2.1.4
  shared_preferences: ^2.3.2
  simple_icons: ^10.1.3
  socket_io_client: ^3.0.0
  url_launcher: ^6.2.5
  webview_flutter: ^4.9.0
  flutter_activity_recognition:
    path: ./flutter_activity_recognition
  device_info_plus: ^11.1.0
  open_file: ^3.5.9
  package_info_plus: ^8.1.0
  permission_handler: ^11.3.1
  two_dimensional_scrollables: ^0.3.3

dev_dependencies:
  leancode_lint: ^14.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/allow_location.png
    - assets/ic_logo_color.png
    - assets/No_Internet_Connection.png
    - assets/delivery-truck.png
    - assets/delivery_done.png
    - assets/cash_collection.png
    - assets/delivery_back.png
    - assets/icon_for_medical_shop.png
    - assets/Map-100x100.bmp
    - assets/overdue.jpg
    - assets/app_logo_big.png
    - assets/visit.png


flutter_native_splash:
  color: "##D7D6DA"
  image: assets/splash.png
  color_dark: "##D7D6DA"
  image_dark: assets/splash.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/app_logo_big.png"
  min_sdk_android: 21