name: rdl_radiant
description: Demonstrates how to use the location plugin.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  awesome_notifications: ^0.9.3+1
  awesome_notifications_core: ^0.9.3
  dio: ^5.6.0
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.1
  flutter_polyline_points: ^2.1.0
  fluttertoast: ^8.2.8
  gap: ^3.0.1
  geocoding: ^3.0.0
  get: ^5.0.0-release-candidate-6
  google_maps_flutter: ^2.9.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.2.2
  location: ^7.0.0
  path_provider: ^2.1.4
  permission_handler: ^11.3.1
  simple_icons: ^10.1.3
  url_launcher: ^6.2.5

dev_dependencies:
  leancode_lint: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/allow_location.png


flutter_native_splash:
  color: "##D7D6DA"
  image: assets/splash.png
  color_dark: "##D7D6DA"
  image_dark: assets/splash.png

  android_12:
    image: assets/splash.png
    icon_background_color: "##D7D6DA"
    image_dark: assets/splash.png
    icon_background_color_dark: "##D7D6DA"